---
apiVersion: v1
kind: Service
metadata:
  name: wall-api-svc
  namespace: api-ns
  labels:
    app.kubernetes.io/name: wall-api
spec:
  selector:
    app.kubernetes.io/name: wall-api
  ports:
    - name: http
      port: 80
      protocol: TCP
      targetPort: 3000
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: wall-ingress
  namespace: api-ns
  annotations:
    cert-manager.io/cluster-issuer: letsencrypt-prod
spec:
  tls:
    - hosts:
        - wall.v3il.xyz
      secretName: api-ingress-tls
  rules:
    - host: wall.v3il.xyz
      http:
        paths:
          - backend:
              service:
                name: wall-api-svc
                port:
                  number: 80
            path: /
            pathType: Prefix
---

